//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Manager_Xamarin {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meeting_Manager_Xamarin.ResourceStrings", typeof(ResourceStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day {0} of every {1} month(s).
        /// </summary>
        internal static string AbsMonthlyPart {
            get {
                return ResourceManager.GetString("AbsMonthlyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute dates.
        /// </summary>
        internal static string AbsoluteDateOption {
            get {
                return ResourceManager.GetString("AbsoluteDateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} year(s) on {1} {2}.
        /// </summary>
        internal static string AbsYearlyPart {
            get {
                return ResourceManager.GetString("AbsYearlyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptCaption {
            get {
                return ResourceManager.GetString("AcceptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose:.
        /// </summary>
        internal static string AcceptDeclineCaption {
            get {
                return ResourceManager.GetString("AcceptDeclineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AcceptedResponse {
            get {
                return ResourceManager.GetString("AcceptedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;ll attend.
        /// </summary>
        internal static string AcceptTitle {
            get {
                return ResourceManager.GetString("AcceptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Attendee.
        /// </summary>
        internal static string AddAttendeeCaption {
            get {
                return ResourceManager.GetString("AddAttendeeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Recipient.
        /// </summary>
        internal static string AddRecipientCaption {
            get {
                return ResourceManager.GetString("AddRecipientCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        internal static string AddressListOption {
            get {
                return ResourceManager.GetString("AddressListOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        internal static string AllDayCaption {
            get {
                return ResourceManager.GetString("AllDayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        internal static string AllDayPart {
            get {
                return ResourceManager.GetString("AllDayPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAP.
        /// </summary>
        internal static string ASAPOption {
            get {
                return ResourceManager.GetString("ASAPOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string AttachCaption {
            get {
                return ResourceManager.GetString("AttachCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string AttachmentsCaption {
            get {
                return ResourceManager.GetString("AttachmentsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string AttachmentsTitle {
            get {
                return ResourceManager.GetString("AttachmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string AttendeesHeader {
            get {
                return ResourceManager.GetString("AttendeesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Direct HTTP.
        /// </summary>
        internal static string AuthHttpOption {
            get {
                return ResourceManager.GetString("AuthHttpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MSAL.
        /// </summary>
        internal static string AuthMsalOption {
            get {
                return ResourceManager.GetString("AuthMsalOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the meeting &apos;{0}&apos;?&quot;.
        /// </summary>
        internal static string CancelInstance {
            get {
                return ResourceManager.GetString("CancelInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel:.
        /// </summary>
        internal static string CancelMeetingCaption {
            get {
                return ResourceManager.GetString("CancelMeetingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the meeting occurence &apos;{0}&apos;?.
        /// </summary>
        internal static string CancelOccurence {
            get {
                return ResourceManager.GetString("CancelOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelOption {
            get {
                return ResourceManager.GetString("CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the meeting series &apos;{0}&apos;?.
        /// </summary>
        internal static string CancelSeries {
            get {
                return ResourceManager.GetString("CancelSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mails found to reply to..
        /// </summary>
        internal static string CantReply {
            get {
                return ResourceManager.GetString("CantReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to MS Graph.
        /// </summary>
        internal static string ConnectCaption {
            get {
                return ResourceManager.GetString("ConnectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ContactsOption {
            get {
                return ResourceManager.GetString("ContactsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contact.
        /// </summary>
        internal static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Meeting.
        /// </summary>
        internal static string CreateMeetingTitle {
            get {
                return ResourceManager.GetString("CreateMeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DailyOption {
            get {
                return ResourceManager.GetString("DailyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} day(s).
        /// </summary>
        internal static string DailyPart {
            get {
                return ResourceManager.GetString("DailyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string DaysCaption {
            get {
                return ResourceManager.GetString("DaysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string DeclineCaption {
            get {
                return ResourceManager.GetString("DeclineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string DeclinedResponse {
            get {
                return ResourceManager.GetString("DeclinedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I won&apos;t attend.
        /// </summary>
        internal static string DeclineTitle {
            get {
                return ResourceManager.GetString("DeclineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Description.
        /// </summary>
        internal static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit response.
        /// </summary>
        internal static string EditResponseOption {
            get {
                return ResourceManager.GetString("EditResponseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  effective {0}.
        /// </summary>
        internal static string EffectivePart {
            get {
                return ResourceManager.GetString("EffectivePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailCaption {
            get {
                return ResourceManager.GetString("EmailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after.
        /// </summary>
        internal static string EndAfterOption {
            get {
                return ResourceManager.GetString("EndAfterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by.
        /// </summary>
        internal static string EndByOption {
            get {
                return ResourceManager.GetString("EndByOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment.
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string EveryCaption {
            get {
                return ResourceManager.GetString("EveryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every.
        /// </summary>
        internal static string EveryPart {
            get {
                return ResourceManager.GetString("EveryPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        internal static string FilesTitle {
            get {
                return ResourceManager.GetString("FilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindRoom.
        /// </summary>
        internal static string FindRoomCaption {
            get {
                return ResourceManager.GetString("FindRoomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ForwardOption {
            get {
                return ResourceManager.GetString("ForwardOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ForwardTitle {
            get {
                return ResourceManager.GetString("ForwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FridayCaption {
            get {
                return ResourceManager.GetString("FridayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FromCaption {
            get {
                return ResourceManager.GetString("FromCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0:h:mm tt} to {1:h:mm tt}.
        /// </summary>
        internal static string FromToPart {
            get {
                return ResourceManager.GetString("FromToPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Direct HTTP.
        /// </summary>
        internal static string GraphHttpOption {
            get {
                return ResourceManager.GetString("GraphHttpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Graph SDK.
        /// </summary>
        internal static string GraphSdkOption {
            get {
                return ResourceManager.GetString("GraphSdkOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string InstanceOption {
            get {
                return ResourceManager.GetString("InstanceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m running late....
        /// </summary>
        internal static string LateOption {
            get {
                return ResourceManager.GetString("LateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operation:.
        /// </summary>
        internal static string MailOperationCaption {
            get {
                return ResourceManager.GetString("MailOperationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string MaximizeCaption {
            get {
                return ResourceManager.GetString("MaximizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string MondayCaption {
            get {
                return ResourceManager.GetString("MondayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string MonthlyOption {
            get {
                return ResourceManager.GetString("MonthlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string MonthsCaption {
            get {
                return ResourceManager.GetString("MonthsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewCaption {
            get {
                return ResourceManager.GetString("NewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoCaption {
            get {
                return ResourceManager.GetString("NoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date.
        /// </summary>
        internal static string NoEndOption {
            get {
                return ResourceManager.GetString("NoEndOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free slots are found.
        /// </summary>
        internal static string NoFreeSlots {
            get {
                return ResourceManager.GetString("NoFreeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not specified.
        /// </summary>
        internal static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response.
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t send response.
        /// </summary>
        internal static string NoResponseOption {
            get {
                return ResourceManager.GetString("NoResponseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurences.
        /// </summary>
        internal static string OccurencesCaption {
            get {
                return ResourceManager.GetString("OccurencesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs .
        /// </summary>
        internal static string OccursPart {
            get {
                return ResourceManager.GetString("OccursPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every.
        /// </summary>
        internal static string OfEveryCaption {
            get {
                return ResourceManager.GetString("OfEveryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string OfMonthCaption {
            get {
                return ResourceManager.GetString("OfMonthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKCaption {
            get {
                return ResourceManager.GetString("OKCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string OnDayCaption {
            get {
                return ResourceManager.GetString("OnDayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnMonthCaption {
            get {
                return ResourceManager.GetString("OnMonthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the.
        /// </summary>
        internal static string OnTheOrdinalCaption {
            get {
                return ResourceManager.GetString("OnTheOrdinalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer:.
        /// </summary>
        internal static string OrganizerCaption {
            get {
                return ResourceManager.GetString("OrganizerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string OrganizerHeader {
            get {
                return ResourceManager.GetString("OrganizerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string OrganizerResponse {
            get {
                return ResourceManager.GetString("OrganizerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original message.
        /// </summary>
        internal static string OriginalMessageCaption {
            get {
                return ResourceManager.GetString("OriginalMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        internal static string RecurrenceCaption {
            get {
                return ResourceManager.GetString("RecurrenceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        internal static string RecurrenceTitle {
            get {
                return ResourceManager.GetString("RecurrenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshCaption {
            get {
                return ResourceManager.GetString("RefreshCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative dates.
        /// </summary>
        internal static string RelativeDateOption {
            get {
                return ResourceManager.GetString("RelativeDateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} {1} of every {2} month(s).
        /// </summary>
        internal static string RelMonthlyPart {
            get {
                return ResourceManager.GetString("RelMonthlyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} year(s) on the {1} {2} of {3}.
        /// </summary>
        internal static string RelYearlyPart {
            get {
                return ResourceManager.GetString("RelYearlyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply All.
        /// </summary>
        internal static string ReplyAllOption {
            get {
                return ResourceManager.GetString("ReplyAllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply All.
        /// </summary>
        internal static string ReplyAllTitle {
            get {
                return ResourceManager.GetString("ReplyAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string ReplyOption {
            get {
                return ResourceManager.GetString("ReplyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string ReplyTitle {
            get {
                return ResourceManager.GetString("ReplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m running late....
        /// </summary>
        internal static string RunningLate {
            get {
                return ResourceManager.GetString("RunningLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string SaturdayCaption {
            get {
                return ResourceManager.GetString("SaturdayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Auth Service implementation:.
        /// </summary>
        internal static string SelectAuthService {
            get {
                return ResourceManager.GetString("SelectAuthService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date:.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Graph Service implementation:.
        /// </summary>
        internal static string SelectGraphService {
            get {
                return ResourceManager.GetString("SelectGraphService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attendee.
        /// </summary>
        internal static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        internal static string SelectRoom {
            get {
                return ResourceManager.GetString("SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectSlotOption {
            get {
                return ResourceManager.GetString("SelectSlotOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendCaption {
            get {
                return ResourceManager.GetString("SendCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mail.
        /// </summary>
        internal static string SendMailTitle {
            get {
                return ResourceManager.GetString("SendMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send response now.
        /// </summary>
        internal static string SendResponseOption {
            get {
                return ResourceManager.GetString("SendResponseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string SeriesOption {
            get {
                return ResourceManager.GetString("SeriesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selection as JSON.
        /// </summary>
        internal static string ShowJsonCaption {
            get {
                return ResourceManager.GetString("ShowJsonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:hh:mm tt}.
        /// </summary>
        internal static string StartFormat {
            get {
                return ResourceManager.GetString("StartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartHeader {
            get {
                return ResourceManager.GetString("StartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on.
        /// </summary>
        internal static string StartOnCaption {
            get {
                return ResourceManager.GetString("StartOnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        internal static string StatusNoResponse {
            get {
                return ResourceManager.GetString("StatusNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string StatusOrganizer {
            get {
                return ResourceManager.GetString("StatusOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string SubjectHeader {
            get {
                return ResourceManager.GetString("SubjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitCaption {
            get {
                return ResourceManager.GetString("SubmitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string SundayCaption {
            get {
                return ResourceManager.GetString("SundayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        internal static string TentativeCaption {
            get {
                return ResourceManager.GetString("TentativeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        internal static string TentativeResponse {
            get {
                return ResourceManager.GetString("TentativeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I might attend.
        /// </summary>
        internal static string TentativeTitle {
            get {
                return ResourceManager.GetString("TentativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string TheOrdinalCaption {
            get {
                return ResourceManager.GetString("TheOrdinalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ThursdayCaption {
            get {
                return ResourceManager.GetString("ThursdayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slots.
        /// </summary>
        internal static string TimeSlotsBtnCaption {
            get {
                return ResourceManager.GetString("TimeSlotsBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slots:.
        /// </summary>
        internal static string TimeSlotsCaption {
            get {
                return ResourceManager.GetString("TimeSlotsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select available time slot.
        /// </summary>
        internal static string TimeSlotsTitle {
            get {
                return ResourceManager.GetString("TimeSlotsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ToCaption {
            get {
                return ResourceManager.GetString("ToCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TuesdayCaption {
            get {
                return ResourceManager.GetString("TuesdayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  until {0}.
        /// </summary>
        internal static string UntilPart {
            get {
                return ResourceManager.GetString("UntilPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string UpCaption {
            get {
                return ResourceManager.GetString("UpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Meeting.
        /// </summary>
        internal static string UpdateMeetingTitle {
            get {
                return ResourceManager.GetString("UpdateMeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from:.
        /// </summary>
        internal static string UserOrContactCaption {
            get {
                return ResourceManager.GetString("UserOrContactCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View:.
        /// </summary>
        internal static string ViewMeetingCaption {
            get {
                return ResourceManager.GetString("ViewMeetingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewOption {
            get {
                return ResourceManager.GetString("ViewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayCaption {
            get {
                return ResourceManager.GetString("WednesdayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string WeeklyOption {
            get {
                return ResourceManager.GetString("WeeklyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        internal static string WeeklyPartFirst {
            get {
                return ResourceManager.GetString("WeeklyPartFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and {0}.
        /// </summary>
        internal static string WeeklyPartLast {
            get {
                return ResourceManager.GetString("WeeklyPartLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}.
        /// </summary>
        internal static string WeeklyPartNext {
            get {
                return ResourceManager.GetString("WeeklyPartNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s) on.
        /// </summary>
        internal static string WeeksCaption {
            get {
                return ResourceManager.GetString("WeeksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string YearlyOption {
            get {
                return ResourceManager.GetString("YearlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        internal static string YearsCaption {
            get {
                return ResourceManager.GetString("YearsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesCaption {
            get {
                return ResourceManager.GetString("YesCaption", resourceCulture);
            }
        }
    }
}
